<?php

namespace NRTest\PetClinicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OwnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OwnerRepository extends EntityRepository
{
	
	public function findAllByLastName($lastName)
	{
		return $this->getEntityManager()
			->createQuery('SELECT o FROM NRTestPetClinicBundle:Owner o WHERE o.lastName LIKE \'%'.$lastName.'%\' ')
			->getResult();
	}
}