<?php

namespace NRTest\PetClinicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SpecialtyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialtyRepository extends EntityRepository
{
}