<?php

namespace NRTest\PetClinicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VisitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitRepository extends EntityRepository
{
}